## The training Data has been downloaded from UCI's database.
# Naive Bayes.

In [21]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
data = pd.read_csv('iris dataset/iris.csv')
data_test = pd.read_csv('iris dataset/iris_test.csv')

data = data.sample(frac=1).reset_index(drop=True)
data_test = data_test.sample(frac=1).reset_index(drop=True)

In [4]:
data

sepal length  sepal width  petal length  petal width            class
0             7.7          3.0           6.1          2.3   Iris-virginica
1             6.1          2.9           4.7          1.4  Iris-versicolor
2             7.4          2.8           6.1          1.9   Iris-virginica
3             5.5          3.5           1.3          0.2      Iris-setosa
4             4.9          3.6           1.4          0.1      Iris-setosa
5             5.1          3.8           1.9          0.4      Iris-setosa
6             5.5          2.3           4.0          1.3  Iris-versicolor
7             5.6          2.7           4.2          1.3  Iris-versicolor
8             4.6          3.2           1.4          0.2      Iris-setosa
9             6.7          3.1           4.7          1.5  Iris-versicolor
10            5.5          2.6           4.4          1.2  Iris-versicolor
11            6.3          2.5           4.9          1.5  Iris-versicolor
12            5.7          2.6           3.5          1.0  Iris-versicolor
13            5.5          2.4           3.8          1.1  Iris-versicolor
14            6.0          2.9           4.5          1.5  Iris-versicolor
15            6.3          2.5           5.0          1.9   Iris-virginica
16            4.4          3.0           1.3          0.2      Iris-setosa
17            6.7          3.3           5.7          2.5   Iris-virginica
18            4.8          3.4           1.6          0.2      Iris-setosa
19            5.5          4.2           1.4          0.2      Iris-setosa
20            4.8          3.0           1.4          0.1      Iris-setosa
21            4.4          2.9           1.4          0.2      Iris-setosa
22            5.1          2.5           3.0          1.1  Iris-versicolor
23            5.8          2.6           4.0          1.2  Iris-versicolor
24            6.4          3.2           5.3          2.3   Iris-virginica
25            6.3          2.8           5.1          1.5   Iris-virginica
26            6.4          2.7           5.3          1.9   Iris-virginica
27            6.2          2.2           4.5          1.5  Iris-versicolor
28            6.0          2.2           4.0          1.0  Iris-versicolor
29            4.5          2.3           1.3          0.3      Iris-setosa
..            ...          ...           ...          ...              ...
90            7.9          3.8           6.4          2.0   Iris-virginica
91            5.2          3.5           1.5          0.2      Iris-setosa
92            5.2          3.4           1.4          0.2      Iris-setosa
93            5.5          2.4           3.7          1.0  Iris-versicolor
94            6.2          3.4           5.4          2.3   Iris-virginica
95            6.1          3.0           4.6          1.4  Iris-versicolor
96            4.9          3.1           1.5          0.2      Iris-setosa
97            5.1          3.5           1.4          0.2      Iris-setosa
98            5.7          2.9           4.2          1.3  Iris-versicolor
99            6.5          2.8           4.6          1.5  Iris-versicolor
100           4.9          3.0           1.4          0.2      Iris-setosa
101           4.6          3.6           1.0          0.2      Iris-setosa
102           5.4          3.9           1.7          0.4      Iris-setosa
103           5.6          2.5           3.9          1.1  Iris-versicolor
104           6.4          3.2           4.5          1.5  Iris-versicolor
105           6.8          3.0           5.5          2.1   Iris-virginica
106           5.9          3.0           5.1          1.8   Iris-virginica
107           4.8          3.1           1.6          0.2      Iris-setosa
108           6.9          3.2           5.7          2.3   Iris-virginica
109           6.4          2.8           5.6          2.2   Iris-virginica
110           6.4          2.8           5.6          2.1   Iris-virginica
111           5.0          2.3

In [31]:
x = data.iloc[:,:-1].values
y = data.iloc[:,4].values

x_test = data_test.iloc[:,:-1].values
y_test = data_test.iloc[:,4].values

In [32]:
classifier = GaussianNB()
classifier.fit(x, y)

GaussianNB(priors=None)

In [33]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = classifier.score(x_test, y_test)
y_pred = classifier.predict(x_test)
print (cm)
print ("Accuracy =", accuracy*100)
'''
CLASSIFICATION REPROT
'''
target_names = ['Iris-setosa', 'Iris-versicolor','Iris-virginica']
print(classification_report(y_test, y_pred, target_names= target_names))

[[10  0  0]
 [ 0  8  2]
 [ 0  1  9]]
Accuracy = 90.0
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.89      0.80      0.84        10
 Iris-virginica       0.82      0.90      0.86        10

    avg / total       0.90      0.90      0.90        30



In [34]:
cm

array([[10,  0,  0],
       [ 0,  8,  2],
       [ 0,  1,  9]])

## --------End of Naive Bayes Code--------

# LOGISTIC REGRESSION CLASSIFICATION

In [35]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [36]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = classifier.score(x_test, y_test)
y_pred = classifier.predict(x_test)
print (cm)
print ("Accuracy =", accuracy*100)
'''
CLASSIFICATION REPROT
'''
target_names = ['Iris-setosa', 'Iris-versicolor','Iris-virginica']
print(classification_report(y_test, y_pred, target_names= target_names))

[[10  0  0]
 [ 0  7  3]
 [ 0  1  9]]
Accuracy = 86.6666666667
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.88      0.70      0.78        10
 Iris-virginica       0.75      0.90      0.82        10

    avg / total       0.88      0.87      0.87        30



### --------End of Logistic RegressionCode--------

# SVM Classification

In [26]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [27]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = classifier.score(x_test, y_test)
y_pred = classifier.predict(x_test)
print (cm)
print ("Accuracy =", accuracy*100)
'''
CLASSIFICATION REPROT
'''
target_names = ['Iris-setosa', 'Iris-versicolor','Iris-virginica']
print(classification_report(y_test, y_pred, target_names= target_names))

[[10  0  0]
 [ 0  8  2]
 [ 0  0 10]]
Accuracy = 93.3333333333
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.80      0.89        10
 Iris-virginica       0.83      1.00      0.91        10

    avg / total       0.94      0.93      0.93        30



The accuracy for each kernel, linear or rbf or poly, is the same. 

### --------End of SVM--------

# Decision Tree Classification

In [29]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x, y)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')

In [30]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = classifier.score(x_test, y_test)
y_pred = classifier.predict(x_test)
print (cm)
print ("Accuracy =", accuracy*100)
'''
CLASSIFICATION REPROT
'''
target_names = ['Iris-setosa', 'Iris-versicolor','Iris-virginica']
print(classification_report(y_test, y_pred, target_names= target_names))

[[10  0  0]
 [ 0  7  3]
 [ 0  0 10]]
Accuracy = 90.0
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.70      0.82        10
 Iris-virginica       0.77      1.00      0.87        10

    avg / total       0.92      0.90      0.90        30



### -------End of Decision Tree--------